# -*- coding: utf-8 -*-
"""API_KEY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-M8LAfi1SBin92fF_mbOBmYjYNCZcBfK
"""

from openai import OpenAI

client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key="",
)
question = input("Enter your question:")

completion = client.chat.completions.create(
  extra_headers={
    # "HTTP-Referer": "<YOUR_SITE_URL>", # Optional. Site URL for rankings on openrouter.ai.
    # "X-Title": "<YOUR_SITE_NAME>", # Optional. Site title for rankings on openrouter.ai.
  },
  extra_body={},
  model="cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
  messages=[
    {
      "role": "user",
      "content": f"{question}"
    }
  ]
)
print(completion.choices[0].message.content)

print(completion)

from openai import OpenAI

client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key="",
)
question= input("Enter your question:")
completion = client.chat.completions.create(
  extra_headers={
    "HTTP-Referer": "<YOUR_SITE_URL>", # Optional. Site URL for rankings on openrouter.ai.
    "X-Title": "<YOUR_SITE_NAME>", # Optional. Site title for rankings on openrouter.ai.
  },
  extra_body={},
  model="mistralai/mistral-small-3.2-24b-instruct:free",
  messages=[
    {
      "role": "user",
      "content": f"{question}"

      }
      ]
)
print(completion.choices[0].message.content)

"""# Template
```
from openai import OpenAI

client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key="my api key",
)
question= input("Enter your question:")
completion = client.chat.completions.create(
  extra_headers={
    "HTTP-Referer": "<YOUR_SITE_URL>", # Optional. Site URL for rankings on openrouter.ai.
    "X-Title": "<YOUR_SITE_NAME>", # Optional. Site title for rankings on openrouter.ai.
  },
  extra_body={},
  model="mistralai/mistral-small-3.2-24b-instruct:free",
  messages=[
    {
      "role": "user",
      "content": f"{question}"
        
      }
      ]
)
print(completion.choices[0].message.content)
```
"""

